<?php

declare(strict_types=1);

namespace App\Commands;

use App\Support\Scaffolding\ResourceSchema;
use App\Support\Scaffolding\ScaffoldRemover;
use App\Support\Scaffolding\StringHelper;
use CodeIgniter\CLI\BaseCommand;
use CodeIgniter\CLI\CLI;

/**
 * Inverse of make:crud — deletes the files generated for a resource and un-wires
 * its routes/services. Useful after a botched scaffold (broken FK target, wrong
 * resource name, abandoned domain) so the developer can retry from a clean tree
 * without manually deleting ~17 files plus editing Services.php.
 *
 * Migrations are NOT auto-rolled-back. The command prints the migration filename
 * so the user can decide whether to run `php spark migrate:rollback` first.
 */
class MakeCrudRemove extends BaseCommand
{
    protected $group = 'Scaffold';
    protected $name = 'make:crud:remove';
    protected $description = 'Remove a resource generated by make:crud (files + service wiring + route block).';
    protected $usage = 'make:crud:remove <Resource> [--domain <Domain>] [--route <slug>] [--dry-run]';
    protected $arguments = [
        'Resource' => 'Resource singular name (e.g. Product, ApiKeyV2)',
    ];
    protected $options = [
        '--domain' => 'Domain folder (default: Catalog) — must match the original make:crud invocation',
        '--route' => 'Route slug plural (default: kebab-case plural of resource)',
        '--dry-run' => 'Show what would be removed without touching the filesystem',
    ];

    public function run(array $params)
    {
        $resourceInput = (string) ($params[0] ?? '');
        if ($resourceInput === '') {
            CLI::error('Resource argument is required. Example: php spark make:crud:remove Product');
            return EXIT_ERROR;
        }

        $resource = StringHelper::studly($resourceInput);
        $domain = StringHelper::studly((string) (CLI::getOption('domain') ?: 'Catalog'));
        $route = (string) (CLI::getOption('route') ?: StringHelper::toKebab(StringHelper::pluralize($resource)));
        $dryRun = CLI::getOption('dry-run') !== null;

        // Build a minimal schema — the remover only reads name/domain/route.
        // softDelete + fields are irrelevant for path computation and trait removal.
        $schema = new ResourceSchema(
            resource: $resource,
            domain: $domain,
            route: $route,
            fields: [],
        );

        if ($dryRun) {
            CLI::write("🔎 DRY RUN — no files will be modified.", 'cyan');
        }

        CLI::write("🗑  Removing scaffold: {$resource} from domain {$domain}", 'cyan');
        CLI::newLine();

        $remover = new ScaffoldRemover();
        $report = $dryRun ? $remover->plan($schema) : $remover->remove($schema);

        if (empty($report['deleted'])
            && $report['routes_cleaned'] === null
            && $report['trait_cleaned'] === null
            && !$report['services_cleaned']
        ) {
            CLI::write("Nothing to remove. Did you mean a different resource or domain?", 'yellow');
            return EXIT_SUCCESS;
        }

        if (!empty($report['deleted'])) {
            CLI::write($dryRun ? 'Would delete:' : 'Deleted:', 'yellow');
            foreach ($report['deleted'] as $path) {
                CLI::write("  - {$path}");
            }
            CLI::newLine();
        }

        if (!empty($report['not_found'])) {
            CLI::write('Skipped (already absent):', 'yellow');
            foreach ($report['not_found'] as $path) {
                CLI::write("  - {$path}");
            }
            CLI::newLine();
        }

        if ($report['routes_cleaned'] !== null) {
            CLI::write(($dryRun ? 'Would un-inject' : 'Un-injected') . " route block from: {$report['routes_cleaned']}", 'green');
        }
        if ($report['trait_cleaned'] !== null) {
            CLI::write(($dryRun ? 'Would un-inject' : 'Un-injected') . " service factories from: {$report['trait_cleaned']}", 'green');
        }
        if ($report['trait_removed'] !== null) {
            CLI::write(($dryRun ? 'Would remove' : 'Removed') . " empty domain trait: {$report['trait_removed']}", 'green');
        }
        if ($report['services_cleaned']) {
            CLI::write(($dryRun ? 'Would un-register' : 'Un-registered') . ' domain trait from app/Config/Services.php', 'green');
        }

        CLI::newLine();
        if ($report['migration'] !== null) {
            CLI::write("⚠ Migration file deleted: {$report['migration']}", 'yellow');
            CLI::write("  If the migration was already applied, run:", 'yellow');
            CLI::write("    php spark migrate:rollback", 'white');
            CLI::write("  …before the next make:crud, or drop the table manually.", 'yellow');
        }

        if (!$dryRun) {
            CLI::write('✅ Scaffold removed.', 'white', 'green');
        }

        return EXIT_SUCCESS;
    }
}
